version: '3.8'

services:
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./data:/var/www/symfony_docker/data
    depends_on:
      - redis

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8089:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis

  redis:
    image: 'redis:7.4.1'
    container_name: recruitis-redis
    ports:
      - 6379:6379
    restart: unless-stopped
