# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    error_controller: App\Controller\ErrorController::show

    http_client:
      scoped_clients:
        recruitisApiClient:
          base_uri: '%env(RECRUITIS_API_BASE_URL)%'
          auth_bearer: '%env(RECRUITIS_API_AUTH_TOKEN)%'

    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    serializer:
      name_converter: serializer.name_converter.camel_case_to_snake_case

    # Note that the session will be started ONLY if you read or write from it.
    session:
      cookie_lifetime: 3600
      storage_factory_id: session.storage.factory.php_bridge

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
